/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package keycloak.jsample.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-08T23:38:49.410+09:00")

@Api(value = "admin", description = "the admin API")
public interface AdminApi {

    @ApiOperation(value = "Admin hello message", nickname = "getAdminMsg", notes = "", response = String.class, tags={ "application-controller", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "message retrival is successful", response = String.class) })
    @RequestMapping(value = "/admin/hello",
        method = RequestMethod.GET)
    ResponseEntity<String> getAdminMsg();

}
